version: '3'
services:
  app:
    build: .
    image: kz/darth-veda:latest
    ports:
      - 8080:8080
    depends_on:
      - mongodb0
    networks:
      - darth
  mongodb0:
    image: mongo:7
    command: mongod --port 27017
    ports:
      - 27017:27017
    networks:
      - darth

networks:
  darth:
    driver: bridge
