version: '3'
services:
  mongodb0:
    image: mongo:7
    mem_limit: 3072m
    mem_reservation: 3072m
    cpus: '3'
    command: mongod --port 27017
    ports:
      - 27017:27017
    networks:
      - darth
  app:
    build: .
    image: kz/darth-veda:latest
    mem_limit: 1024m
    mem_reservation: 1024m
    cpus: '1'
    environment:
      - SERVER_PORT=8080
      - SERVER_MODE=server
      - SERVER_BACKEND=mongo
    ports:
      - 8080:8080
    depends_on:
      - mongodb0
    networks:
      - darth

networks:
  darth:
    driver: bridge
