version: '3.9'
services:
  mongodb:
    image: mongo:7.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=darth
    ports:
      - 27017:27017
    networks:
      - darth

networks:
  darth:
    driver: bridge

