version: '3.9'
services:
  mongodb0:
    image: mongo:7
    ports:
      - 27017:27017
    networks:
      - darth
  mongodb1:
    image: mongo:7
    command: mongod --port 27018
    ports:
      - 27018:27018
    networks:
      - darth

networks:
  darth:
    driver: bridge

