version: '3.9'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-darth-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01-darth-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - darth-net

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-darth-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es02-darth-data:/usr/share/elasticsearch/data
    networks:
      - darth-net

volumes:
  es01-darth-data:
    driver: local
  es02-darth-data:
    driver: local

networks:
  darth-net:
    driver: bridge

